/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/XctgALmaDeT
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function Timeline() {
	return (
		(<div className="p-6 sm:p-10">
			<div className="text-center mb-8">
				<div className="flex items-center gap-2 justify-center">
					<div className='h-[1px] w-full bg-slate-500'></div>
					<h2 className="text-3xl font-bold">Timeline</h2>
					<div className='h-[1px] w-full bg-slate-500'></div>
				</div>
				<p className="text-gray-500 dark:text-gray-400">A look back at my journey so far.</p>
			</div>
			<div
				className="after:absolute after:inset-y-0 after:w-px after:bg-gray-500/20 relative pl-6 after:left-0 grid gap-10 dark:after:bg-gray-400/20">
				<div className="grid gap-1 text-sm relative">
					<div
						className="aspect-square w-3 bg-gray-900 rounded-full absolute left-0 translate-x-[-29.5px] z-10 top-1 dark:bg-gray-50" />
					<div className="font-medium">March 14, 1879</div>
					<div className="font-medium">Invention of Quantum Computing</div>
					<div className="text-gray-500 dark:text-gray-400">
						Scientists at a leading research institution unveil a groundbreaking breakthrough in quantum computing.
					</div>
				</div>
				<div className="grid gap-1 text-sm relative">
					<div
						className="aspect-square w-3 bg-gray-900 rounded-full absolute left-0 translate-x-[-29.5px] z-10 top-1 dark:bg-gray-50" />
					<div className="font-medium">April 1, 1939</div>
					<div className="font-medium">First Quantum Computer</div>
					<div className="text-gray-500 dark:text-gray-400">
						The first quantum computer is built by a team of researchers in a laboratory in the United States.
					</div>
				</div>
				<div className="grid gap-1 text-sm relative">
					<div
						className="aspect-square w-3 bg-gray-900 rounded-full absolute left-0 translate-x-[-29.5px] z-10 top-1 dark:bg-gray-50" />
					<div className="font-medium">June 12, 1954</div>
					<div className="font-medium">Quantum Computing Research</div>
					<div className="text-gray-500 dark:text-gray-400">
						A group of scientists in Europe publish a paper on quantum computing research.
					</div>
				</div>
				<div className="grid gap-1 text-sm relative">
					<div
						className="aspect-square w-3 bg-gray-900 rounded-full absolute left-0 translate-x-[-29.5px] z-10 top-1 dark:bg-gray-50" />
					<div className="font-medium">December 31, 1979</div>
					<div className="font-medium">Quantum Computing Breakthrough</div>
					<div className="text-gray-500 dark:text-gray-400">
						A team of researchers in Asia makes a significant breakthrough in quantum computing.
					</div>
				</div>
			</div>
		</div>)
	);
}
